package com.example.adminservice.entity.enums;

public enum Permission {

    ADD_CATEGORY,
    ADD_PERMISSIONS_ROLE,
    ADD_PRODUCT,
    ADD_ROLE,

    DELETE_CATEGORY,
    DELETE_PERMISSIONS_ROLE,
    DELETE_PRODUCT,
    DELETE_ROLE,

    DELETE_USER,
    DOWNLOAD_ATTACHMENT,
    EDIT_CATEGORY,
    EDIT_PRODUCT,

    EDIT_ROLE,
    EDIT_USER,
    MANAGE_ROLE_TO_USER,
    UPLOAD_ATTACHMENT,
    VIEW_CATEGORY,
    VIEW_PRODUCT,

    VIEW_ROLE,
    VIEW_USER,

}
